server:
  port: 8080

jodconverter:
  local:
    enabled: true
    office-home: C:\Program Files (x86)\OpenOffice 4
    max-tasks-per-process: 10
    port-numbers: 8100


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_project
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.projectssm.model

#showSql
logging:
  level:
    com:
      projectssm:
        mapper : debug

